version: '3.8'


services:
  postgresql:
    container_name: postgres-food-delivery
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST=${TYPEORM_HOST}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    command: postgres